"""Macro-MCTS pack layer (outer-iter body, cheap expand, MCTS policy)."""

__all__ = [
    "BoardSnapshot",
    "FirstPassBorderResult",
    "MacroMctsRunner",
    "MctsAgent",
    "MidPackStagesResult",
    "PackIterCtx",
    "RefinePackBox",
    "VoidLeakOrchResult",
    "ancestors",
    "bind_epoch",
    "board_snapshot_from_selection",
    "cheap_pack_cache_key",
    "credit_motif_on_nest_survival",
    "credit_void_niche_from_iter",
    "execute_pack",
    "finalize_iter_mcts",
    "inject_cohorts_and_bind_graph",
    "invalidate_cheap_cache",
    "leaf_reward",
    "macro_increase_path",
    "path_probe_budget",
    "make_execute_fn",
    "maybe_invalidate_cheap_cache",
    "merge_void_elite_with_archive",
    "native_geoms_from_transforms",
    "niche_amaf_key",
    "pack_execute_snapshot",
    "path_reward_beats",
    "prep_selection_free",
    "prep_selection_freeze",
    "realize_selection",
    "record_mcts_expand",
    "record_outer_iter_expand",
    "rim_before_for_selection",
    "run_compose_refine_pack",
    "run_first_pass_border_pack",
    "run_mid_pack_stages",
    "run_mcts_multi_sim",
    "run_pack_stages",
    "run_post_pack_stage",
    "run_uh_post_rim_compose",
    "run_void_leak_and_niche_credit",
    "schedule_prep_selection_free",
    "selection_coverage_pct",
    "stamp_arena_amaf",
    "stamp_pack_stage",
    "with_isolated_pack_cache",
]

_LAZY = {
    "BoardSnapshot": ("nest_graph.graph", "BoardSnapshot"),
    "FirstPassBorderResult": ("nest_graph.pack.ctx", "FirstPassBorderResult"),
    "MacroMctsRunner": ("nest_graph.pack.runner", "MacroMctsRunner"),
    "MctsAgent": ("nest_graph.graph", "MctsAgent"),
    "MidPackStagesResult": ("nest_graph.pack.ctx", "MidPackStagesResult"),
    "PackIterCtx": ("nest_graph.pack.ctx", "PackIterCtx"),
    "RefinePackBox": ("nest_graph.pack.ctx", "RefinePackBox"),
    "VoidLeakOrchResult": ("nest_graph.pack.ctx", "VoidLeakOrchResult"),
    "ancestors": ("nest_graph.pack.macro_path", "ancestors"),
    "bind_epoch": ("nest_graph.pack.epoch", "bind_epoch"),
    "board_snapshot_from_selection": ("nest_graph.pack.execute", "board_snapshot_from_selection"),
    "cheap_pack_cache_key": ("nest_graph.pack.cache_key", "cheap_pack_cache_key"),
    "credit_motif_on_nest_survival": ("nest_graph.pack.motif_credit", "credit_motif_on_nest_survival"),
    "credit_void_niche_from_iter": ("nest_graph.pack.motif_credit", "credit_void_niche_from_iter"),
    "execute_pack": ("nest_graph.pack.execute", "execute_pack"),
    "finalize_iter_mcts": ("nest_graph.pack.credit", "finalize_iter_mcts"),
    "inject_cohorts_and_bind_graph": ("nest_graph.pack.epoch", "inject_cohorts_and_bind_graph"),
    "invalidate_cheap_cache": ("nest_graph.pack.cheap", "invalidate_cheap_cache"),
    "leaf_reward": ("nest_graph.graph", "leaf_reward"),
    "macro_increase_path": ("nest_graph.pack.macro_path", "macro_increase_path"),
    "path_probe_budget": ("nest_graph.pack.macro_path", "path_probe_budget"),
    "make_execute_fn": ("nest_graph.pack.execute", "make_execute_fn"),
    "maybe_invalidate_cheap_cache": ("nest_graph.pack.cheap", "maybe_invalidate_cheap_cache"),
    "merge_void_elite_with_archive": ("nest_graph.pack.motif_credit", "merge_void_elite_with_archive"),
    "native_geoms_from_transforms": ("nest_graph.pack.geoms", "native_geoms_from_transforms"),
    "niche_amaf_key": ("nest_graph.pack.motif_credit", "niche_amaf_key"),
    "pack_execute_snapshot": ("nest_graph.pack.cheap", "pack_execute_snapshot"),
    "path_reward_beats": ("nest_graph.graph", "path_reward_beats"),
    "prep_selection_free": ("nest_graph.pack.execute", "prep_selection_free"),
    "prep_selection_freeze": ("nest_graph.pack.execute", "prep_selection_freeze"),
    "realize_selection": ("nest_graph.pack.epoch", "realize_selection"),
    "record_mcts_expand": ("nest_graph.pack.execute", "record_mcts_expand"),
    "record_outer_iter_expand": ("nest_graph.pack.execute", "record_outer_iter_expand"),
    "rim_before_for_selection": ("nest_graph.pack.stages", "rim_before_for_selection"),
    "run_compose_refine_pack": ("nest_graph.pack.stages", "run_compose_refine_pack"),
    "run_first_pass_border_pack": ("nest_graph.pack.stages", "run_first_pass_border_pack"),
    "run_mid_pack_stages": ("nest_graph.pack.stages", "run_mid_pack_stages"),
    "run_mcts_multi_sim": ("nest_graph.pack.execute", "run_mcts_multi_sim"),
    "run_pack_stages": ("nest_graph.pack.execute", "run_pack_stages"),
    "run_post_pack_stage": ("nest_graph.pack.stages", "run_post_pack_stage"),
    "run_uh_post_rim_compose": ("nest_graph.pack.stages", "run_uh_post_rim_compose"),
    "run_void_leak_and_niche_credit": ("nest_graph.pack.credit", "run_void_leak_and_niche_credit"),
    "schedule_prep_selection_free": ("nest_graph.pack.execute", "schedule_prep_selection_free"),
    "selection_coverage_pct": ("nest_graph.pack.geoms", "selection_coverage_pct"),
    "stamp_arena_amaf": ("nest_graph.pack.execute", "stamp_arena_amaf"),
    "stamp_pack_stage": ("nest_graph.pack.execute", "stamp_pack_stage"),
    "with_isolated_pack_cache": ("nest_graph.pack.cheap", "with_isolated_pack_cache"),
}


def __getattr__(name: str):
    if name in _LAZY:
        mod_name, attr = _LAZY[name]
        import importlib

        mod = importlib.import_module(mod_name)
        val = getattr(mod, attr)
        globals()[name] = val
        return val
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
